import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./stitch_ayush_ministry_portal_redesign/**/*.{html,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#84c39b",
        "on-secondary-fixed": "#331200",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-tertiary-container": "#adb4ce",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#bec6e0",
        "background": "#f7f9fb",
        "tertiary-container": "#3f465b",
        "tertiary": "#283044",
        "outline": "#707971",
        "on-background": "#191c1e",
        "inverse-primary": "#95d4ac",
        "primary-fixed": "#b0f1c7",
        "primary": "#003820",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed-variant": "#3f465c",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#0f5132",
        "on-tertiary-fixed": "#131b2e",
        "secondary-container": "#fd8a42",
        "on-surface-variant": "#404942",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
        "primary-container": "#0f5132",
        "on-primary-fixed": "#002111",
        "on-secondary-fixed-variant": "#763300",
        "primary-fixed-dim": "#95d4ac",
        "tertiary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#2d6a48",
        "on-surface": "#191c1e",
        "secondary-fixed": "#ffdbca",
        "surface": "#f7f9fb",
        "secondary": "#9b4500",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#ffb68e",
        "outline-variant": "#c0c9c0",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "on-secondary-container": "#682c00",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "margin": "2rem",
        "gutter": "1.25rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
      },
      fontFamily: {
        "label-lg": ["Public Sans"],
        "body-md": ["Inter"],
        "display-lg": ["Public Sans"],
        "headline-md": ["Public Sans"],
        "label-md": ["Public Sans"],
        "body-sm": ["Inter"],
        "headline-xl-mobile": ["Public Sans"],
        "headline-xl": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "tabular-data": ["Inter"],
        "display-lg-mobile": ["Public Sans"],
        "title-md": ["Public Sans"],
        "headline-sm": ["Public Sans"],
        "body-lg": ["Inter"],
        "label-sm": ["Public Sans"],
      },
      fontSize: {
        "label-lg": ["13px", { lineHeight: "16px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" },
        ],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-xl-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700" },
        ],
        "headline-xl": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "tabular-data": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "display-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "700" },
        ],
        "title-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": [
          "10px",
          { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
